# Generated by Django 4.0.1 on 2022-07-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendane',
            name='is_present',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('MATHS', 'Maths'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry')], default='', max_length=10),
        ),
    ]
