# Generated by Django 4.1.3 on 2022-11-15 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('taskId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('priority', models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], default='Medium', max_length=8)),
                ('description', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 11, 15, 21, 8, 6, 414812))),
            ],
        ),
    ]
