# Generated by Django 4.1.3 on 2022-11-15 15:42

import datetime
from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 21, 12, 29, 389918)),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.IntegerField(auto_created=random.Random.randint, primary_key=True, serialize=False),
        ),
    ]
