# Generated by Django 4.1.3 on 2022-11-16 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0003_alter_task_created_date_alter_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 10, 13, 6, 1079)),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
