# Generated by Django 4.1.3 on 2022-11-16 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0005_alter_task_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='udated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
