# Generated by Django 4.1.3 on 2022-11-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0007_task_id_alter_task_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
