# Generated by Django 4.1.3 on 2022-11-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0008_remove_task_id_alter_task_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], max_length=8),
        ),
    ]
