# Generated by Django 4.1.3 on 2022-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
